// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EditContestController from "./edit_contest_controller"
application.register("edit-contest", EditContestController)

import OptionController from "./option_controller"
application.register("option", OptionController)

import PropController from "./prop_controller"
application.register("prop", PropController)
