// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import EditContestController from "controllers/edit_contest_controller"
application.register("edit-contest", EditContestController)

import EditEnterableController from "controllers/edit_enterable_controller"
application.register("edit-enterable", EditEnterableController)

import EditLiveController from "controllers/edit_live_controller"
application.register("edit-live", EditLiveController)

import OptionController from "controllers/option_controller"
application.register("option", OptionController)

import PropController from "controllers/prop_controller"
application.register("prop", PropController)

import ShareController from "controllers/share_controller"
application.register("share", ShareController)

import EnterController from "controllers/enter_controller"
application.register("enter", EnterController)

