databases:
  - name: alissapropbet
    databaseName: alissapropbet
    user: deploy

services:
  - type: web
    name: alissapropbet
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: alissapropbet
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
